version: '3.5'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8007:80"
      - "4438:443"
    volumes:
      - ./docker/nginx/hosts:/etc/nginx/conf.d
      - ./:/var/www
    depends_on:
      - phalcon
  phalcon:
    build:
      context: ./
      dockerfile: ./docker/phalcon/Dockerfile
    container_name: phalcon_php

    user: "${UID}"
    volumes:
      - ./:/var/www
    ports:
      - 22:22
  db:
    build:
      context: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phalconDB
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: mysql_db
    ports:
      - "3306:3306"
    tty: true
