<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search users
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["users/new", "Create users"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "users/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmailid" class="col-sm-2 control-label">Emailid</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["emailid", "size" => 30, "class" => "form-control", "id" => "fieldEmailid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldContactnumber" class="col-sm-2 control-label">ContactNumber</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["contactNumber", "type" => "number", "class" => "form-control", "id" => "fieldContactnumber"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
